### PR TITLE
DvMap_OP_2.1_A4.svg

### PR DESCRIPTION
**Pull request by Kowgan**
OPM changes:
- Darkened Urlum system color palette
- Fix Eeloo surface-orbit value (450 to 540)
- Fix Eeloo total dV value (11040 to 11140)
- Fix Wal Orbit-Tal Intercept value (150 to 380)
- Fix Tal total dV value (10490 to 10720)

### CODE REVIEW

**Comment by merlinthered** [comment]
Could you explain how the changed values come to be? Did I make some calculation error or mistyped something?

The color palette for Urlum is purposefully brighter, because it will not look that way when printed. Have you tried printing the second page? Your printer can not reproduce a neon blue color, so it will look much darker in reality. My printer currently has some shitty off-brand ink, but I think even brand cyan ink will not be that bright.

I do like your color choice though. I'll see if my printer can reproduce something like that.

**Comment by Kowgan** [comment]
According to Misucat's map, yes, apparently you misplaced some numbers when copying it to your version.

Here is Misucat's map: http://i.imgur.com/nuYvn8O.png
On Eeloo, the Surface-to-orbit path says "540", not "450". Then, I replaced the total dV value to fit accordingly. ... And apparently, I missed something in the calcs as well.
3400(kerbin to low orbit) + 950(LKO to kerbin SOI edge) + 1390 + 1660 + 1580 + 1120 + 490 + 540 = 11130 (not 11140, as I've put in the pull request).

You wrote the Wal-Tal transfer value as 150, while Misucat's map shows it as 380. I can only presume that you looked at the wrong node when copying; the next one (tal intercept-tal low orbit), which is 150.
And as such, after correcting it, I updated the final dV value to match it. Luckly, this time I didn't miscalculate anything. :)
3400 + 950 + 1600 + 1490 + 940 + 900 + 810 + 380 + 150 + 100 = 10720

Now, the colors. I just noticed the Urlum path cyan was too bright for the big amount of white icons next to it (from Urlum intercept to low orbit). I thought "Well, if he darkened Kerbol's line a few days ago (which wasn't even as bright as this cyan), he'll probably want to darken this cyan as well." So I took the iniciative. :)
But that's just a suggestion. Since the main intent of this is to be printed, and you say it looks good on paper, you might as well just leave the original colors, then. :)

I hope this clarifies my changes.

**Comment by merlinthered** [comment]
Thanks. Yellow looks quite a bit brighter on paper than cyan. Since we probably also want people to be able to read the map without printing it, I guess we should tone down the Urlum colors a bit regardless.

**Comment by merlinthered** [comment]
I am closing this pull request as I have applied the changes to my branch. I don't want to mess anything up by auto-merging svg files. I made the Urlum system still a bit brighter than you did. The hue you chose is pretty nice. The colors look pretty good when I print them now.

**Pull request closed without merging**
