### PR TITLE
DvMap_A4.svg experimental update

### PR DESCRIPTION
**Pull request by Kowgan**
SKETCH: Added Time between transfer windows to return to Kerbin:
- This is the average time between transfer windows from a planet to Kerbin. This data is useful for those who use life support mods, so they know how long they'll have to survive in a planet before the next window to return home.
- This is a sketch. I just placed the raw data there; if you can find a better place/method to show this data, feel free to modify as you see fit.

Reduced 1K from the Eve-to-Orbit dV.

### CODE REVIEW

**Comment by merlinthered** [comment]
I like this idea.

How is the variance of the actual times? Averages won't help you much when the individual times vary wildly.

Would the values be very different when you calculate the actual average time spent at the target planet? (Transfer window Kerbin->Target, time to Target, then use the time to the next transfer window back after arrival.)

Where did the new value for Eve originate?

**Comment by Kowgan** [comment]
On my calcs, I used 6 window passes for each planet. Most of them are very consistent, varying little (differing no more than 10 days from the average). Except Eeloo. Eeloo have a pretty big window, changing according to time of flight, and plus, each next window seems to come a bit later than the previous one, until a certain point, when it lowers down again. There's not much we can do about this anyway.

Again: The idea here is to let people know averagely the maximum period they'll have to stay in a planet before the next window opens again and they can burn their way back home. And for this purpose, I think these numbers do the job very well.

The new Eve value originated from a guy on IRC (#KSPOfficial) not satisfied with the current 10k value. He made a (not 100% convincing) video showing that he could reach low Eve orbit with little more than 8k dV, and provided the .craft file in the video description ( https://www.youtube.com/watch?v=O2UDwytRfhU ).

I personally tried it myself with the given craft, but I had a result of 10k dV spent after reaching low orbit, just like my previous tests. So, I assume that my Eve ascent might not be the most efficient, and, refusing to go with 8k, I lowered it to 9k instead.
But my personal choice would be to keep the current value, rather than lowering it.

(Anyway, my modem blew up while I was writing this, and my ISP said I'll have a guy coming here with a new one on monday. So, expect to have me offline at least until then.)

**Comment by Kowgan** [comment]
There are more people saying they're achieving orbit with less than 9k dV. Maybe we should change it to 8k afterall.

**Comment by merlinthered** [comment]
I'm for having numbers that people will typically need (whatever that means) instead of the absolute minimum possible. Since I don't have experience with any planets other than Kerbin and Duna, I can't really comment. You're the numbers guy. You decide.

**Comment by Kowgan** [comment]
Thanks for the input. It's much appreciated. We'll go with 9K, then. Also, I'm yet to download the new OPM version and make the calcs for the new planet...

**Comment by Kowgan** [comment]
Please, discard this pull request.

**Pull request closed without merging**
