### PR TITLE
dV Map OP2 2.3.1

### PR DESCRIPTION
**Pull request by Kowgan**
- Added the two new Neidon moons
- Changed logo position.
  You may review the design for this as you see fit. I tried my best to fit everything in there, but one may argue that it's an ugly result. :)

### CODE REVIEW

**Comment by merlinthered** [comment]
I'd try to position both moons on the same side of the planet, and avoid so many direction changes in the lines. You can make a little more space by moving the Plock arm further to the left I guess. 

I'd try something myself, but I'm kind of busy until mid-December.

**Comment by Kowgan** [comment]
Updated. Also fixed the version number.

**Comment by merlinthered** [comment]
Hi, 

sorry for being absent. I've been kind of busy with other things and I don't have email notifications enabled (I really should).

Are all these pull requests still valid? If so, I will try to find the time and merge them.

**Comment by Kowgan** [comment]
No worries. Real life comes first.
This pull requests is outdated. Since I don't have write access on the main branch, I created a fork ( https://github.com/Kowgan/ksp_cheat_sheets ), so everyone could have access to the updated stuff. I'll send a pull request from there.

**Pull request closed without merging**
